# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='label',
            field=models.CharField(max_length=200, unique=True, verbose_name=b'Device identifier'),
        ),
    ]
